services:
  postgres:
    image: postgres:latest
    container_name: postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: ecommerce
    volumes:
      - postgres-data:/var/lib/postgresql/data
    ports:
      - "5432:5432"

  pgadmin:
    image: dpage/pgadmin4
    container_name: pgadmin
    environment:
      PGADMIN_DEFAULT_EMAIL: ngozika1105@gmail.com
      PGADMIN_DEFAULT_PASSWORD: postgres
    ports:
      - "5050:80"
    depends_on:
      - postgres

  redis:
    image: redis:alpine
    container_name: redis_store
    ports: 
      - "6379:6379"
    volumes:
      - redis-data:/data"

  backend:
    build:
      context: ./backend        # Relative to docker-compose.yml
      dockerfile: docker/Dockerfile  # Relative to the context directory
    container_name: backend
    ports:
      - "5000:5000"
    environment:
      DATABASE_URL: postgres://postgres:postgres@postgres:5432/ecommerce
    depends_on:
      - postgres
      - redis

  frontend:
    build:
      context: ./frontend/myecommerce   # Relative to docker-compose.yml
      dockerfile: Dockerfile            # Dockerfile inside 'myecommerce' directory
    container_name: frontend
    ports:
      - "3000:3000"
    environment:
      NEXT_PUBLIC_BACKEND_URL: http://backend:5000
    depends_on:
      - backend

volumes:
  postgres-data:
  redis-data: