
import type { Metadata } from "next";
import { inter } from '@/app/ui/font'
import "./globals.css";
import { UserProvider } from '@/app/context/userContext';
import { CartProvider } from "@/app/context/cartContext";
import { ProductProvider } from "./context/productContext";
import { PaystackProvider } from "./context/paystackContext";
import NavBar from "@/app/ui/navbar";
import Footer from '@/app/ui/footer';
import { OrderProvider } from '@/app/context/orderContext';



export const metadata: Metadata = {
  title: "Family shop",
  description: "Generated by create-next-app",
};


interface RootLayoutProps {
  children: React.ReactNode;
}

export default function RootLayout({ children }: RootLayoutProps) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <UserProvider>
          <CartProvider>
            <OrderProvider>
              <ProductProvider>
                <PaystackProvider>
                  <NavBar />
                  <main className="h-auto bg-gray-100">{children}</main>
                  <Footer />
                </PaystackProvider>
              </ProductProvider>
            </OrderProvider>
          </CartProvider>
        </UserProvider>
      </body>
    </html>

  );
}
