import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import { UserProvider } from '@/app/context/userContext'

import NavBar from '@/app/ui/navabar';



const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default  function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
 
  return (
    
    <html lang="en">
      <body className={inter.className}  >
      <UserProvider>
        <NavBar />
          <main>{children}</main>
          </UserProvider>
        </body>
    </html>
    
  );
}
