import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import { UserProvider } from '@/app/context/userContext';
import { CartProvider } from "@/app/context/cartContext";
import { ProductProvider } from "@/app/context/productContext";
import NavBarWrapper from "@/app/context/navbarWrapper";
import Footer from '@/app/ui/footer'
import { OrderProvider } from '@/app/context/orderContext';


const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Family shop",
  description: "Generated by create next app",
};


interface RootLayoutProps {
  children: React.ReactNode;
}

export default function RootLayout({ children }: RootLayoutProps) {


  return (

    <html lang="en">
      <body className={inter.className}  >
        <ProductProvider>
          <UserProvider>
            <CartProvider>
              <OrderProvider>

                <NavBarWrapper />
                <main className="h-auto bg-gray-100">{children}</main>
                <Footer />
              </OrderProvider>
            </CartProvider>
          </UserProvider>
        </ProductProvider>
      </body>
    </html>

  );
}
